# Copyright: Ankitects Pty Ltd and contributors
# License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html

"""Cache-versioning tests for the ReadyMCAT generated-ladder sidecar.

The reviewer reuses a per-note generated ladder from
``readymcat_generated_ladders.json`` on every later miss. When the generation /
grounding logic changes, a ladder produced by the old logic must NOT be
replayed (that reintroduced bug 2: a stale ``#io-overlay``-CSS ladder about a
card's source code). ``cached_ladder`` therefore ignores any cache stamped with
a different :data:`CACHE_VERSION`, so stale entries are regenerated with the
current grounding.

These exercise only the pure cache helpers (file + JSON), so they need neither
the network nor the core generator.
"""

from __future__ import annotations

import json
from pathlib import Path

import aqt.readymcat_ladder_gen as ladder_gen


def _rung() -> dict:
    return {
        "question": "What is the committed step of glycolysis?",
        "options": ["PFK-1", "Hexokinase", "Aldolase"],
        "correctIndex": 0,
        "explanation": "PFK-1 catalyses the committed step of glycolysis.",
    }


def _write_cache_file(tmp_path: Path, version: object, ladders: dict) -> str:
    """Write a sidecar next to a (fake) collection and return the collection path
    the way the reviewer passes it (``col.path``)."""
    (tmp_path / ladder_gen.CACHE_FILENAME).write_text(
        json.dumps({"version": version, "ladders": ladders}), encoding="utf-8"
    )
    return str(tmp_path / "collection.anki2")


def test_cached_ladder_ignores_stale_version(tmp_path: Path) -> None:
    col = _write_cache_file(
        tmp_path, ladder_gen.CACHE_VERSION - 1, {"7": [_rung(), _rung()]}
    )
    # A ladder generated by an older grounding version is stale: return None so
    # the reviewer regenerates it with the current grounding.
    assert ladder_gen.cached_ladder(col, 7) is None


def test_cached_ladder_ignores_missing_version(tmp_path: Path) -> None:
    # A pre-versioning cache file (no "version" key) is treated as stale too.
    path = tmp_path / ladder_gen.CACHE_FILENAME
    path.write_text(json.dumps({"ladders": {"7": [_rung()]}}), encoding="utf-8")
    assert ladder_gen.cached_ladder(str(tmp_path / "collection.anki2"), 7) is None


def test_cached_ladder_returns_current_version_entry(tmp_path: Path) -> None:
    col = _write_cache_file(tmp_path, ladder_gen.CACHE_VERSION, {"7": [_rung()]})
    cached = ladder_gen.cached_ladder(col, 7)
    assert cached is not None
    assert cached[0]["question"] == _rung()["question"]


def test_write_cache_stamps_current_version_and_drops_stale(tmp_path: Path) -> None:
    col = _write_cache_file(tmp_path, ladder_gen.CACHE_VERSION - 1, {"7": [_rung()]})
    # Writing a fresh entry migrates the file to the current version and drops
    # the stale one, so a mismatched-version cache cannot linger on disk.
    ladder_gen._write_cache(col, 9, [_rung()])

    data = json.loads(
        (tmp_path / ladder_gen.CACHE_FILENAME).read_text(encoding="utf-8")
    )
    assert data["version"] == ladder_gen.CACHE_VERSION
    assert "9" in data["ladders"]
    assert "7" not in data["ladders"]
    assert ladder_gen.cached_ladder(col, 9) is not None
    assert ladder_gen.cached_ladder(col, 7) is None
