#!/usr/bin/env python3
# Copyright: ReadyMCAT contributors
# License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html
"""Author, build, and validate the ReadyMCAT Chemical & Physical Foundations (C/P)
FREE-RESPONSE (type-in answer) question bank.

This is the free-response complement to the multiple-choice bank
(``chem_phys.json``). Every item asks for a SHORT typed answer -- a term, a
number+unit, or a short phrase -- so it is auto-gradeable with normalized string
/ key-term / numeric matching (no AI needed at the grading layer). Numeric items
declare their expected value, unit, and a tolerance.

Every item is ORIGINAL, authored for ReadyMCAT and grounded in a free / openly
licensed source (OpenStax, LibreTexts). No item is copied or paraphrased from any
copyrighted or paid question bank (UWorld, Kaplan, Blueprint, AAMC paid/official
materials). The public AAMC "What's on the MCAT Exam?" content outline is used
only for the topic list / category IDs (already encoded in taxonomy.json).

The bank is held here as Python data so JSON escaping and structure are always
valid. Running this script:
  1. writes free_response_chem_phys.json (a JSON array of items conforming to the
     ReadyMCAT C/P free-response schema), and
  2. re-loads it and runs the standalone validator
     (validate_free_response_chem_phys.py), printing a coverage report.

Run:  python3 build_free_response_chem_phys.py
Exits 0 on success, 1 on any validation failure.
"""

from __future__ import annotations

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "free_response_chem_phys.json")


# --- source registry helpers (name / url / license) ------------------------
# Each returns a fresh dict so json.dump serializes it inline per item.

def cp2e(chapter: str) -> dict:
    return {"name": f"OpenStax College Physics 2e, {chapter}",
            "url": "https://openstax.org/details/books/college-physics-2e",
            "license": "CC BY 4.0"}


def chem2e(chapter: str) -> dict:
    return {"name": f"OpenStax Chemistry 2e, {chapter}",
            "url": "https://openstax.org/details/books/chemistry-2e",
            "license": "CC BY 4.0"}


def ochem(chapter: str) -> dict:
    return {"name": f"OpenStax Organic Chemistry, {chapter}",
            "url": "https://openstax.org/details/books/organic-chemistry",
            "license": "CC BY 4.0"}


def bio2e(chapter: str) -> dict:
    return {"name": f"OpenStax Biology 2e, {chapter}",
            "url": "https://openstax.org/details/books/biology-2e",
            "license": "CC BY 4.0"}


def ltchem(topic: str) -> dict:
    return {"name": f"LibreTexts Chemistry \u2014 {topic}",
            "url": "https://chem.libretexts.org",
            "license": "CC BY-NC-SA 4.0"}


def ltphys(topic: str) -> dict:
    return {"name": f"LibreTexts Physics \u2014 {topic}",
            "url": "https://phys.libretexts.org",
            "license": "CC BY-NC-SA 4.0"}


# --- item constructors -----------------------------------------------------

def sub(stem: str, accepted: list, explanation: str) -> dict:
    """A guiding teach-on-miss ladder step (a short-answer sub-question)."""
    return {"stem": stem, "answer_type": "free_response",
            "accepted_answers": accepted, "explanation": explanation}


def item(id, cat, subtopic, prompt, accepted, key_terms, model_answer,
         explanation, difficulty, cognitive_level, source, subquestions) -> dict:
    return {
        "id": id,
        "section": "C/P",
        "aamc_category": cat,
        "subtopic": subtopic,
        "answer_type": "free_response",
        "prompt": prompt,
        "accepted_answers": accepted,
        "key_terms": key_terms,
        "model_answer": model_answer,
        "explanation": explanation,
        "difficulty": difficulty,
        "cognitive_level": cognitive_level,
        "source": source,
        "subquestions": subquestions,
    }


# ===========================================================================
#  4A -- Translational motion, forces, work, energy, equilibrium
# ===========================================================================

def _cat_4A() -> list:
    return [
        item("fr-cp-4A-1", "4A", "Kinematics: free fall",
             "A ball is released from rest and falls freely for 3.0 s (g = 10 m/s\u00b2, neglect air resistance). What is its speed just before landing? Give the value with units.",
             ["30 m/s", "30 m s^-1", "30 m/s^1", "v = 30 m/s", "30"],
             ["unit: m/s", "tolerance: \u00b10.5 m/s", "v = g t"],
             "v = v\u2080 + g t = 0 + (10 m/s\u00b2)(3.0 s) = 30 m/s.",
             "From rest v\u2080 = 0, so speed grows linearly as v = g t. The distance fallen (\u00bd g t\u00b2 = 45 m) is a common trap; it is a length, not a speed.",
             "easy", "application", cp2e("Ch. 2: Kinematics"),
             [sub("An object dropped from rest has what initial speed v\u2080 (in m/s)?",
                  ["0", "0 m/s", "zero"],
                  "\"Released from rest\" means v\u2080 = 0."),
              sub("Write the equation for speed after time t for an object falling from rest.",
                  ["v = g t", "v=gt", "gt", "v = at"],
                  "With v\u2080 = 0 and a = g, v = v\u2080 + a t reduces to v = g t."),
              sub("Evaluate v = g t for g = 10 m/s\u00b2 and t = 3.0 s (give m/s).",
                  ["30 m/s", "30"],
                  "(10 m/s\u00b2)(3.0 s) = 30 m/s.")]),

        item("fr-cp-4A-2", "4A", "Kinematics: projectile motion",
             "A marble rolls off a table 1.25 m high with a horizontal speed of 3.0 m/s (g = 10 m/s\u00b2). How far from the base of the table does it land? Give the value with units.",
             ["1.5 m", "1.5 meters", "x = 1.5 m", "1.5"],
             ["unit: m", "tolerance: \u00b10.1 m", "horizontal range"],
             "Fall time from h = \u00bd g t\u00b2: t = \u221a(2h/g) = \u221a(2\u00b71.25/10) = \u221a0.25 = 0.50 s. Range x = v\u2093 t = (3.0)(0.50) = 1.5 m.",
             "Horizontal and vertical motions are independent. The drop height sets the time aloft; the horizontal speed then sets the distance.",
             "medium", "application", cp2e("Ch. 3: Two-Dimensional Kinematics"),
             [sub("With no air resistance, what happens to the horizontal velocity during the flight?",
                  ["stays constant", "constant", "unchanged", "remains 3.0 m/s"],
                  "No horizontal force means a\u2093 = 0, so v\u2093 is constant."),
              sub("How long is the marble airborne? Use h = \u00bd g t\u00b2 with h = 1.25 m, g = 10 m/s\u00b2 (give s).",
                  ["0.50 s", "0.5 s", "0.50"],
                  "t = \u221a(2h/g) = \u221a0.25 = 0.50 s; time aloft depends only on the drop height."),
              sub("Using t = 0.50 s and v\u2093 = 3.0 m/s, find the horizontal distance (give m).",
                  ["1.5 m", "1.5"],
                  "x = v\u2093 t = (3.0)(0.50) = 1.5 m.")]),

        item("fr-cp-4A-3", "4A", "Newton's second law",
             "A constant net force gives a 2.0 kg cart an acceleration of 3.0 m/s\u00b2. What is the magnitude of the net force? Give the value with units.",
             ["6.0 N", "6 N", "F = 6 N", "6"],
             ["unit: N", "tolerance: \u00b10.1 N", "F = m a"],
             "Newton's second law: F_net = m a = (2.0 kg)(3.0 m/s\u00b2) = 6.0 N.",
             "Force equals mass times acceleration; the newton is kg\u00b7m/s\u00b2.",
             "easy", "application", cp2e("Ch. 4: Dynamics: Newton's Laws of Motion"),
             [sub("State Newton's second law relating net force, mass, and acceleration.",
                  ["F = m a", "F=ma", "force = mass x acceleration", "net force = m a"],
                  "F_net = m a."),
              sub("Evaluate (2.0 kg)(3.0 m/s\u00b2) (give N).",
                  ["6.0 N", "6 N", "6"],
                  "2.0 \u00d7 3.0 = 6.0 N."),
              sub("If the same net force acted on a 4.0 kg cart, what acceleration results (m/s\u00b2)?",
                  ["1.5 m/s^2", "1.5 m/s\u00b2", "1.5"],
                  "a = F/m = 6.0/4.0 = 1.5 m/s\u00b2; doubling mass halves acceleration.")]),

        item("fr-cp-4A-4", "4A", "Friction",
             "A 10 kg crate slides across a level floor with coefficient of kinetic friction 0.30 (g = 10 m/s\u00b2). What horizontal force keeps it moving at constant velocity? Give the value with units.",
             ["30 N", "F = 30 N", "30"],
             ["unit: N", "tolerance: \u00b10.5 N", "f = \u03bc_k N"],
             "At constant velocity a = 0, so applied force = kinetic friction. N = mg = (10)(10) = 100 N, so f_k = \u03bc_k N = (0.30)(100) = 30 N.",
             "Kinetic friction is \u03bc_k times the normal force; on a level floor the normal force equals the weight.",
             "medium", "application", cp2e("Ch. 5: Further Applications of Newton's Laws: Friction"),
             [sub("For a crate on a horizontal floor, what does the normal force equal (in N)?",
                  ["100 N", "mg", "m g", "100"],
                  "Vertical equilibrium gives N = mg = (10)(10) = 100 N."),
              sub("Write the equation for kinetic friction in terms of \u03bc_k and N.",
                  ["f = \u03bc_k N", "f = mu_k N", "f=\u03bcN", "friction = coefficient x normal force"],
                  "Kinetic friction equals the coefficient times the normal force."),
              sub("Compute (0.30)(100 N) (give N).",
                  ["30 N", "30"],
                  "f_k = (0.30)(100) = 30 N, which balances the applied force at constant velocity.")]),

        item("fr-cp-4A-5", "4A", "Inclined plane",
             "A block is released from rest on a frictionless incline angled 30\u00b0 above the horizontal (g = 10 m/s\u00b2). What is its acceleration down the incline? Give the value with units.",
             ["5.0 m/s^2", "5.0 m/s\u00b2", "5 m/s^2", "a = 5 m/s^2", "5"],
             ["unit: m/s^2", "tolerance: \u00b10.1 m/s^2", "a = g sin\u03b8"],
             "Along a frictionless incline a = g sin\u03b8 = (10)(sin 30\u00b0) = (10)(0.50) = 5.0 m/s\u00b2.",
             "Only the component of gravity parallel to the surface accelerates the block; that component is g sin\u03b8.",
             "medium", "application", cp2e("Ch. 4-5: Newton's Laws / Inclined planes"),
             [sub("What component of gravitational acceleration acts along a frictionless incline of angle \u03b8?",
                  ["g sin\u03b8", "g sin theta", "gsin\u03b8", "g\u00b7sin\u03b8"],
                  "The parallel component is g sin\u03b8; the perpendicular component g cos\u03b8 is balanced by the normal force."),
              sub("What is sin 30\u00b0?",
                  ["0.5", "0.50", "1/2"],
                  "sin 30\u00b0 = 0.5."),
              sub("Compute g sin\u03b8 = (10 m/s\u00b2)(0.5) (give m/s\u00b2).",
                  ["5.0 m/s^2", "5 m/s^2", "5"],
                  "a = (10)(0.5) = 5.0 m/s\u00b2.")]),

        item("fr-cp-4A-6", "4A", "Torque and static equilibrium",
             "On a seesaw pivoted at its center, a 300 N child sits 1.0 m left of the pivot. How far right of the pivot must a 200 N child sit to balance it? Give the distance with units.",
             ["1.5 m", "d = 1.5 m", "1.5"],
             ["unit: m", "tolerance: \u00b10.05 m", "torque balance"],
             "Balance requires equal and opposite torques: (300 N)(1.0 m) = (200 N)(d) \u2192 d = 300/200 = 1.5 m.",
             "Static equilibrium means net torque = 0. Torque is force \u00d7 lever arm, so the lighter child must sit farther out.",
             "medium", "application", cp2e("Ch. 9: Statics and Torque"),
             [sub("For a balanced seesaw, what must be true of the net torque about the pivot?",
                  ["zero", "net torque = 0", "torques are equal", "0"],
                  "Rotational equilibrium requires the clockwise and counterclockwise torques to be equal (net torque zero)."),
              sub("Write the torque-balance equation for this seesaw.",
                  ["300(1.0) = 200(d)", "300 x 1.0 = 200 x d", "(300)(1.0)=(200)d", "300 = 200 d"],
                  "Torque = force \u00d7 distance on each side: (300)(1.0) = (200)(d)."),
              sub("Solve (300)(1.0) = (200)(d) for d (give m).",
                  ["1.5 m", "1.5"],
                  "d = 300/200 = 1.5 m.")]),

        item("fr-cp-4A-7", "4A", "Work by a constant force",
             "A worker pushes a box 4.0 m across the floor with a constant 25 N force directed along the motion. How much work does the worker do? Give the value with units.",
             ["100 J", "W = 100 J", "100"],
             ["unit: J", "tolerance: \u00b11 J", "W = F d cos\u03b8"],
             "W = F d cos\u03b8 = (25 N)(4.0 m)(cos 0\u00b0) = (25)(4.0)(1) = 100 J.",
             "Work is force times displacement times the cosine of the angle between them; here the force is along the motion (\u03b8 = 0, cos = 1).",
             "easy", "application", cp2e("Ch. 7: Work, Energy, and Energy Resources"),
             [sub("Write the equation for work done by a constant force at angle \u03b8 to the displacement.",
                  ["W = F d cos\u03b8", "W = Fd cos theta", "W=Fdcos\u03b8", "work = F d cos\u03b8"],
                  "W = F d cos\u03b8."),
              sub("What is cos 0\u00b0 (force along the motion)?",
                  ["1", "1.0", "one"],
                  "cos 0\u00b0 = 1, so all of the force does work."),
              sub("Compute (25 N)(4.0 m)(1) (give J).",
                  ["100 J", "100"],
                  "W = 100 J.")]),

        item("fr-cp-4A-8", "4A", "Kinetic energy",
             "What is the kinetic energy of a 2.0 kg object moving at 3.0 m/s? Give the value with units.",
             ["9.0 J", "9 J", "KE = 9 J", "9"],
             ["unit: J", "tolerance: \u00b10.1 J", "KE = 1/2 m v^2"],
             "KE = \u00bd m v\u00b2 = \u00bd (2.0)(3.0)\u00b2 = \u00bd (2.0)(9.0) = 9.0 J.",
             "Kinetic energy scales with the square of speed, so doubling the speed would quadruple KE.",
             "easy", "application", cp2e("Ch. 7: Work, Energy, and Energy Resources"),
             [sub("Write the equation for kinetic energy.",
                  ["KE = 1/2 m v^2", "KE = \u00bd m v\u00b2", "1/2 mv^2", "KE=0.5mv^2"],
                  "KE = \u00bd m v\u00b2."),
              sub("Evaluate v\u00b2 for v = 3.0 m/s (give m\u00b2/s\u00b2).",
                  ["9.0", "9", "9 m^2/s^2"],
                  "(3.0)\u00b2 = 9.0."),
              sub("Compute \u00bd (2.0)(9.0) (give J).",
                  ["9.0 J", "9 J", "9"],
                  "KE = \u00bd(2.0)(9.0) = 9.0 J.")]),

        item("fr-cp-4A-9", "4A", "Conservation of mechanical energy",
             "An object is dropped from rest at a height of 5.0 m (g = 10 m/s\u00b2, no air resistance). What is its speed just before it hits the ground? Give the value with units.",
             ["10 m/s", "v = 10 m/s", "10"],
             ["unit: m/s", "tolerance: \u00b10.5 m/s", "mgh = 1/2 m v^2"],
             "Energy conservation: mgh = \u00bd m v\u00b2 \u2192 v = \u221a(2 g h) = \u221a(2\u00b710\u00b75.0) = \u221a100 = 10 m/s.",
             "Gravitational PE converts entirely to KE; the mass cancels, so speed depends only on height and g.",
             "medium", "application", cp2e("Ch. 7: Work, Energy, and Energy Resources"),
             [sub("As the object falls, gravitational potential energy converts to what form of energy?",
                  ["kinetic energy", "kinetic", "KE"],
                  "PE \u2192 KE with no losses (no friction/air resistance)."),
              sub("Set mgh = \u00bd m v\u00b2 and solve for v.",
                  ["v = sqrt(2gh)", "v = \u221a(2gh)", "sqrt(2gh)", "v=\u221a(2gh)"],
                  "The mass cancels: v = \u221a(2gh)."),
              sub("Compute \u221a(2\u00b710\u00b75.0) (give m/s).",
                  ["10 m/s", "10"],
                  "\u221a100 = 10 m/s.")]),

        item("fr-cp-4A-10", "4A", "Power",
             "A motor does 600 J of work in 4.0 s. What is its average power output? Give the value with units.",
             ["150 W", "P = 150 W", "150"],
             ["unit: W", "tolerance: \u00b11 W", "P = W/t"],
             "P = W/t = 600 J / 4.0 s = 150 W.",
             "Power is the rate of doing work; one watt is one joule per second.",
             "easy", "application", cp2e("Ch. 7: Work, Energy, and Energy Resources"),
             [sub("Write the equation relating power, work, and time.",
                  ["P = W/t", "P=W/t", "power = work/time", "P = W / t"],
                  "Power is work per unit time."),
              sub("Compute 600 J \u00f7 4.0 s (give W).",
                  ["150 W", "150"],
                  "600/4.0 = 150 W."),
              sub("What is the SI unit of power, and what is it equal to?",
                  ["watt", "W", "J/s", "joule per second"],
                  "The watt (W) equals one joule per second.")]),

        item("fr-cp-4A-11", "4A", "Momentum and impulse",
             "A 0.50 kg ball moving at 4.0 m/s is brought to rest. What is the magnitude of the impulse delivered to the ball? Give the value with units.",
             ["2.0 kg\u00b7m/s", "2.0 kg m/s", "2.0 N\u00b7s", "2.0 N s", "2"],
             ["unit: kg\u00b7m/s", "tolerance: \u00b10.1 kg\u00b7m/s", "impulse = change in momentum"],
             "Impulse equals the change in momentum: J = \u0394p = m\u0394v = (0.50)(4.0 \u2212 0) = 2.0 kg\u00b7m/s (equivalently 2.0 N\u00b7s).",
             "Impulse and momentum share units: kg\u00b7m/s = N\u00b7s. Stopping the ball removes all of its momentum.",
             "medium", "application", cp2e("Ch. 8: Linear Momentum and Collisions"),
             [sub("The impulse on an object equals its change in what quantity?",
                  ["momentum", "change in momentum", "\u0394p", "linear momentum"],
                  "Impulse\u2013momentum theorem: J = \u0394p."),
              sub("Write the equation for (linear) momentum.",
                  ["p = m v", "p=mv", "momentum = mass x velocity", "p = mv"],
                  "Momentum p = m v."),
              sub("Compute \u0394p = m\u0394v = (0.50 kg)(4.0 m/s) (give kg\u00b7m/s).",
                  ["2.0 kg\u00b7m/s", "2.0 kg m/s", "2.0 N\u00b7s", "2"],
                  "\u0394p = (0.50)(4.0) = 2.0 kg\u00b7m/s.")]),

        item("fr-cp-4A-12", "4A", "Simple harmonic motion (pendulum)",
             "What is the period of a simple pendulum of length 1.0 m (g = 9.8 m/s\u00b2)? Give the value with units.",
             ["2.0 s", "2.0 seconds", "T = 2.0 s", "2.0"],
             ["unit: s", "tolerance: \u00b10.1 s", "T = 2\u03c0\u221a(L/g)"],
             "T = 2\u03c0\u221a(L/g) = 2\u03c0\u221a(1.0/9.8) = 2\u03c0(0.319) \u2248 2.0 s.",
             "The period of a simple pendulum depends only on length and g (for small angles), not on mass or amplitude.",
             "medium", "application", cp2e("Ch. 16: Oscillatory Motion and Waves"),
             [sub("Write the period formula for a simple pendulum.",
                  ["T = 2\u03c0\u221a(L/g)", "T = 2 pi sqrt(L/g)", "2\u03c0\u221a(L/g)", "T=2\u03c0\u221a(L/g)"],
                  "T = 2\u03c0\u221a(L/g)."),
              sub("Does increasing the bob's mass change the period of a simple pendulum? (yes/no)",
                  ["no", "no change", "does not change", "independent of mass"],
                  "Mass cancels; the period is independent of mass (for small oscillations)."),
              sub("Evaluate 2\u03c0\u221a(1.0/9.8) (give s).",
                  ["2.0 s", "2.0", "2 s"],
                  "\u221a(1.0/9.8) \u2248 0.319, and 2\u03c0(0.319) \u2248 2.0 s.")]),
    ]


# ===========================================================================
#  4B -- Fluids, gases, and gas exchange
# ===========================================================================

def _cat_4B() -> list:
    return [
        item("fr-cp-4B-1", "4B", "Density and specific gravity",
             "An object has a mass of 30 g and a volume of 10 cm\u00b3. What is its density? Give the value with units.",
             ["3.0 g/cm^3", "3.0 g/cm\u00b3", "3 g/cm^3", "3.0 g/mL", "3"],
             ["unit: g/cm^3", "tolerance: \u00b10.1 g/cm^3", "\u03c1 = m/V"],
             "\u03c1 = m/V = 30 g / 10 cm\u00b3 = 3.0 g/cm\u00b3.",
             "Density is mass per unit volume; 1 cm\u00b3 = 1 mL, so 3.0 g/cm\u00b3 = 3.0 g/mL. Its specific gravity (relative to water) is 3.0.",
             "easy", "application", cp2e("Ch. 11: Fluid Statics"),
             [sub("Write the equation for density.",
                  ["\u03c1 = m/V", "rho = m/V", "density = mass/volume", "\u03c1=m/V"],
                  "Density is mass divided by volume."),
              sub("Compute 30 g \u00f7 10 cm\u00b3 (give g/cm\u00b3).",
                  ["3.0 g/cm^3", "3 g/cm^3", "3"],
                  "30/10 = 3.0 g/cm\u00b3."),
              sub("What is this object's specific gravity relative to water (\u03c1_water = 1.0 g/cm\u00b3)?",
                  ["3.0", "3", "3.0 (dimensionless)"],
                  "Specific gravity = \u03c1_object/\u03c1_water = 3.0/1.0 = 3.0 (unitless).")]),

        item("fr-cp-4B-2", "4B", "Buoyancy (Archimedes' principle)",
             "A fully submerged object displaces 2.0 \u00d7 10\u207b\u00b3 m\u00b3 of water (\u03c1 = 1000 kg/m\u00b3, g = 10 m/s\u00b2). What is the buoyant force on it? Give the value with units.",
             ["20 N", "F_b = 20 N", "20"],
             ["unit: N", "tolerance: \u00b10.5 N", "F_b = \u03c1 V g"],
             "F_b = \u03c1_fluid V_displaced g = (1000)(2.0\u00d710\u207b\u00b3)(10) = 20 N.",
             "The buoyant force equals the weight of the displaced fluid (Archimedes' principle).",
             "medium", "application", cp2e("Ch. 11: Fluid Statics \u2014 Archimedes' Principle"),
             [sub("Archimedes' principle: the buoyant force equals the weight of what?",
                  ["displaced fluid", "the fluid displaced", "displaced water", "weight of displaced fluid"],
                  "F_b equals the weight of the fluid displaced by the object."),
              sub("Write the buoyant-force formula in terms of \u03c1, V, and g.",
                  ["F_b = \u03c1 V g", "F = rho V g", "\u03c1Vg", "F_b=\u03c1Vg"],
                  "F_b = \u03c1_fluid V_displaced g."),
              sub("Compute (1000)(2.0\u00d710\u207b\u00b3)(10) (give N).",
                  ["20 N", "20"],
                  "= 20 N.")]),

        item("fr-cp-4B-3", "4B", "Hydrostatic (gauge) pressure",
             "What is the gauge pressure due to the water at a depth of 10 m (\u03c1 = 1000 kg/m\u00b3, g = 10 m/s\u00b2)? Give the value in pascals.",
             ["1.0 \u00d7 10^5 Pa", "100000 Pa", "1.0e5 Pa", "100 kPa", "100000"],
             ["unit: Pa", "tolerance: \u00b12000 Pa", "P = \u03c1 g h"],
             "Gauge pressure P = \u03c1 g h = (1000)(10)(10) = 1.0 \u00d7 10\u2075 Pa (= 100 kPa).",
             "Hydrostatic (gauge) pressure grows linearly with depth; absolute pressure would add atmospheric (\u2248101 kPa).",
             "medium", "application", cp2e("Ch. 11: Fluid Statics \u2014 Pressure"),
             [sub("Write the equation for gauge pressure at depth h in a fluid.",
                  ["P = \u03c1 g h", "P = rho g h", "\u03c1gh", "P=\u03c1gh"],
                  "Gauge pressure P = \u03c1 g h."),
              sub("Compute (1000)(10)(10) (give Pa).",
                  ["100000 Pa", "1.0 x 10^5 Pa", "100 kPa", "100000"],
                  "= 1.0\u00d710\u2075 Pa."),
              sub("Does this depth pressure depend on the cross-sectional area of the water column? (yes/no)",
                  ["no", "no it does not", "independent of area"],
                  "Hydrostatic pressure depends only on \u03c1, g, and depth h \u2014 not on area or total volume.")]),

        item("fr-cp-4B-4", "4B", "Pascal's principle (hydraulics)",
             "In a hydraulic lift, the input piston has area 0.010 m\u00b2 and the output piston has area 0.10 m\u00b2. If 50 N is applied to the input, what force appears at the output? Give the value with units.",
             ["500 N", "F_2 = 500 N", "500"],
             ["unit: N", "tolerance: \u00b15 N", "F2 = F1 A2/A1"],
             "Pascal's principle: pressure is transmitted equally, so F\u2082 = F\u2081(A\u2082/A\u2081) = 50\u00d7(0.10/0.010) = 50\u00d710 = 500 N.",
             "The pressure P = F/A is the same on both pistons, so force scales with area \u2014 the basis of hydraulic force multiplication.",
             "medium", "application", cp2e("Ch. 11: Fluid Statics \u2014 Pascal's Principle"),
             [sub("Pascal's principle: an applied pressure is transmitted how throughout an enclosed fluid?",
                  ["equally", "undiminished", "uniformly", "equally in all directions"],
                  "Pressure is transmitted equally (undiminished) to every part of the fluid."),
              sub("Because pressure is equal on both pistons, write F\u2082 in terms of F\u2081, A\u2081, A\u2082.",
                  ["F2 = F1 A2/A1", "F2 = F1(A2/A1)", "F_2 = F_1 A_2/A_1", "F1 A2/A1"],
                  "Setting F\u2081/A\u2081 = F\u2082/A\u2082 gives F\u2082 = F\u2081(A\u2082/A\u2081)."),
              sub("Compute 50 N \u00d7 (0.10/0.010) (give N).",
                  ["500 N", "500"],
                  "Area ratio = 10, so F\u2082 = 50\u00d710 = 500 N.")]),

        item("fr-cp-4B-5", "4B", "Continuity equation",
             "An incompressible fluid flows at 2.0 m/s through a pipe. Where the pipe's cross-sectional area is half as large, what is the fluid speed? Give the value with units.",
             ["4.0 m/s", "4 m/s", "v_2 = 4 m/s", "4"],
             ["unit: m/s", "tolerance: \u00b10.1 m/s", "A1 v1 = A2 v2"],
             "Continuity: A\u2081v\u2081 = A\u2082v\u2082. With A\u2082 = A\u2081/2, v\u2082 = v\u2081(A\u2081/A\u2082) = 2.0\u00d72 = 4.0 m/s.",
             "For an incompressible fluid the volume flow rate is constant, so narrowing the pipe speeds the fluid up.",
             "medium", "application", cp2e("Ch. 12: Fluid Dynamics \u2014 Flow Rate and Continuity"),
             [sub("Write the continuity equation for an incompressible fluid.",
                  ["A1 v1 = A2 v2", "A\u2081v\u2081 = A\u2082v\u2082", "A1v1=A2v2", "Av = constant"],
                  "The volume flow rate Av is constant: A\u2081v\u2081 = A\u2082v\u2082."),
              sub("If area is halved, how does speed change to keep Av constant?",
                  ["doubles", "speed doubles", "increases by 2", "x2"],
                  "Halving the area doubles the speed."),
              sub("Compute the new speed from v\u2081 = 2.0 m/s (give m/s).",
                  ["4.0 m/s", "4 m/s", "4"],
                  "v\u2082 = 2\u00d72.0 = 4.0 m/s.")]),

        item("fr-cp-4B-6", "4B", "Bernoulli's principle",
             "According to Bernoulli's principle, in a horizontal pipe where the fluid speed increases, how does the fluid's pressure change? Answer in one word.",
             ["lower", "decreases", "it decreases", "drops", "lowers"],
             ["lower", "decreases", "inverse relationship"],
             "It decreases. At constant height, P + \u00bd\u03c1v\u00b2 is constant, so higher speed means lower pressure.",
             "Bernoulli's equation conserves energy per unit volume; faster-moving fluid carries more of its energy as kinetic energy, leaving less as pressure.",
             "medium", "recall", cp2e("Ch. 12: Fluid Dynamics \u2014 Bernoulli's Equation"),
             [sub("Write Bernoulli's equation (name the three terms that sum to a constant).",
                  ["P + 1/2 \u03c1 v^2 + \u03c1 g h", "P + \u00bd\u03c1v\u00b2 + \u03c1gh", "pressure + kinetic + potential", "P+\u00bd\u03c1v\u00b2+\u03c1gh = constant"],
                  "P + \u00bd\u03c1v\u00b2 + \u03c1gh = constant along a streamline."),
              sub("At constant height, if \u00bd\u03c1v\u00b2 (the kinetic term) increases, what must happen to P?",
                  ["decreases", "must decrease", "lower", "goes down"],
                  "The sum is fixed, so P falls as the kinetic term rises."),
              sub("Higher fluid speed therefore corresponds to ____ pressure. (one word)",
                  ["lower", "less", "reduced"],
                  "Higher speed \u2194 lower pressure.")]),

        item("fr-cp-4B-7", "4B", "Viscous flow (Poiseuille's law)",
             "By Poiseuille's law, volume flow rate through a tube is proportional to the fourth power of the radius. If the radius doubles at constant pressure difference, by what factor does the flow rate increase? Give the numeric factor.",
             ["16", "16x", "16 times", "factor of 16"],
             ["dimensionless", "exact", "r^4 dependence"],
             "Q \u221d r\u2074, so doubling r multiplies Q by 2\u2074 = 16.",
             "The steep r\u2074 dependence is why small changes in vessel radius have large effects on blood flow.",
             "medium", "application", cp2e("Ch. 12: Fluid Dynamics \u2014 Viscosity and Poiseuille's Law"),
             [sub("In Poiseuille's law, the flow rate is proportional to the radius raised to what power?",
                  ["4", "fourth", "r^4", "4th"],
                  "Q \u221d r\u2074."),
              sub("Evaluate 2 raised to that power.",
                  ["16", "2^4", "sixteen"],
                  "2\u2074 = 16."),
              sub("So doubling the radius multiplies the flow rate by what factor?",
                  ["16", "16x", "sixteen"],
                  "Flow rate increases 16-fold.")]),

        item("fr-cp-4B-8", "4B", "Ideal gas law",
             "What volume does 2.0 mol of an ideal gas occupy at 1.0 atm and 273 K? Use R = 0.0821 L\u00b7atm/(mol\u00b7K). Give the value in liters.",
             ["44.8 L", "44.8 liters", "45 L", "44.8"],
             ["unit: L", "tolerance: \u00b10.5 L", "V = nRT/P"],
             "V = nRT/P = (2.0)(0.0821)(273)/(1.0) = 44.8 L.",
             "At STP (273 K, 1 atm) one mole of ideal gas occupies 22.4 L, so two moles occupy 44.8 L.",
             "medium", "application", chem2e("Ch. 9: Gases \u2014 The Ideal Gas Law"),
             [sub("Rearrange PV = nRT to solve for volume V.",
                  ["V = nRT/P", "V=nRT/P", "nRT/P"],
                  "V = nRT/P."),
              sub("What volume does 1 mole of ideal gas occupy at STP?",
                  ["22.4 L", "22.4 liters", "22.4"],
                  "The molar volume at STP is 22.4 L."),
              sub("Compute (2.0)(0.0821)(273)/(1.0) (give L).",
                  ["44.8 L", "44.8", "45 L"],
                  "= 44.8 L (\u2248 2 \u00d7 22.4 L).")]),

        item("fr-cp-4B-9", "4B", "Dalton's law of partial pressures",
             "A gas mixture has a total pressure of 1.0 atm. If one component has a mole fraction of 0.25, what is its partial pressure? Give the value with units.",
             ["0.25 atm", "P_A = 0.25 atm", "0.25"],
             ["unit: atm", "tolerance: \u00b10.01 atm", "P_A = X_A P_total"],
             "Partial pressure P_A = X_A \u00b7 P_total = (0.25)(1.0 atm) = 0.25 atm.",
             "Each gas contributes pressure in proportion to its mole fraction; the partial pressures sum to the total (Dalton's law).",
             "easy", "application", chem2e("Ch. 9: Gases \u2014 Dalton's Law"),
             [sub("Write the relationship between a gas's partial pressure, its mole fraction, and the total pressure.",
                  ["P_A = X_A P_total", "P = X P_total", "partial pressure = mole fraction x total", "P_A=X_A\u00b7P"],
                  "P_A = X_A P_total."),
              sub("Compute (0.25)(1.0 atm) (give atm).",
                  ["0.25 atm", "0.25"],
                  "= 0.25 atm."),
              sub("Dalton's law: the partial pressures of all components sum to what?",
                  ["total pressure", "the total pressure", "P_total", "1.0 atm"],
                  "\u03a3 P_i = P_total.")]),

        item("fr-cp-4B-10", "4B", "Kinetic-molecular theory / Graham's law",
             "By Graham's law, how many times faster does hydrogen gas (H\u2082, M = 2 g/mol) effuse compared with oxygen gas (O\u2082, M = 32 g/mol)? Give the numeric factor.",
             ["4", "4x", "4 times", "4:1"],
             ["dimensionless", "exact", "rate \u221d 1/\u221aM"],
             "Rate \u221d 1/\u221aM, so rate_H2/rate_O2 = \u221a(M_O2/M_H2) = \u221a(32/2) = \u221a16 = 4.",
             "Lighter molecules move faster at a given temperature, so they effuse more quickly \u2014 the ratio goes as the square root of the inverse molar-mass ratio.",
             "medium", "application", chem2e("Ch. 9: Gases \u2014 Effusion and Diffusion (Graham's Law)"),
             [sub("In Graham's law, effusion rate is proportional to 1 over the square root of what property?",
                  ["molar mass", "molar mass (M)", "mass", "M"],
                  "Rate \u221d 1/\u221aM."),
              sub("Form the ratio: rate_H2/rate_O2 = \u221a(M_O2/M_H2). Plug in the molar masses.",
                  ["\u221a(32/2)", "sqrt(32/2)", "\u221a16", "sqrt(16)"],
                  "= \u221a(32/2) = \u221a16."),
              sub("Evaluate \u221a16.",
                  ["4", "four"],
                  "\u221a16 = 4, so H\u2082 effuses 4\u00d7 faster.")]),

        item("fr-cp-4B-11", "4B", "Henry's law (gas solubility)",
             "By Henry's law, if the partial pressure of a gas above a liquid triples (temperature constant), by what factor does the dissolved gas concentration change? Give the numeric factor.",
             ["3", "3x", "3 times", "triples"],
             ["dimensionless", "exact", "C = k P"],
             "Henry's law: C = k_H P, so C \u221d P. Tripling the partial pressure triples the dissolved concentration (factor 3).",
             "This linear pressure\u2013solubility relationship underlies gas exchange and, e.g., the fizz when a soda bottle is depressurized.",
             "easy", "application", chem2e("Ch. 11: Solutions and Colloids \u2014 Henry's Law"),
             [sub("Write Henry's law relating dissolved concentration C and partial pressure P.",
                  ["C = k P", "C = k_H P", "C=kP", "concentration = k times pressure"],
                  "C = k_H P (solubility is proportional to partial pressure)."),
              sub("Because C \u221d P, tripling P changes C by what factor?",
                  ["3", "triples", "x3"],
                  "C scales directly with P."),
              sub("If instead the partial pressure were halved, the dissolved concentration would do what?",
                  ["halve", "halves", "decrease by half", "drop to half"],
                  "C \u221d P, so halving P halves C.")]),
    ]


# ===========================================================================
#  4C -- Electrochemistry and electrical circuits
# ===========================================================================

def _cat_4C() -> list:
    return [
        item("fr-cp-4C-1", "4C", "Coulomb's law",
             "Two point charges of +1.0 \u03bcC each are separated by 1.0 m in vacuum (k = 9.0 \u00d7 10\u2079 N\u00b7m\u00b2/C\u00b2). What is the magnitude of the electrostatic force between them? Give the value with units.",
             ["9.0 \u00d7 10^-3 N", "0.009 N", "9.0e-3 N", "9 mN", "9.0 \u00d7 10^-3"],
             ["unit: N", "tolerance: \u00b15%", "F = k q1 q2 / r^2"],
             "F = k q\u2081q\u2082/r\u00b2 = (9.0\u00d710\u2079)(1.0\u00d710\u207b\u2076)(1.0\u00d710\u207b\u2076)/(1.0)\u00b2 = 9.0\u00d710\u207b\u00b3 N.",
             "Coulomb's law gives the force between point charges; it falls off as 1/r\u00b2. Like charges repel, unlike attract.",
             "medium", "application", cp2e("Ch. 18: Electric Charge and Electric Field"),
             [sub("Write Coulomb's law for the force between two point charges.",
                  ["F = k q1 q2 / r^2", "F = kq1q2/r^2", "F=kq\u2081q\u2082/r\u00b2", "kq1q2/r^2"],
                  "F = k q\u2081q\u2082 / r\u00b2."),
              sub("What is 1.0 \u03bcC in coulombs?",
                  ["1.0 x 10^-6 C", "1e-6 C", "0.000001 C", "1.0 \u00d7 10^-6 C"],
                  "1 \u03bcC = 1\u00d710\u207b\u2076 C."),
              sub("Compute (9.0\u00d710\u2079)(1.0\u00d710\u207b\u2076)(1.0\u00d710\u207b\u2076)/(1.0)\u00b2 (give N).",
                  ["9.0 x 10^-3 N", "0.009 N", "9 mN", "9.0e-3 N"],
                  "(9.0\u00d710\u2079)(1\u00d710\u207b\u00b9\u00b2) = 9.0\u00d710\u207b\u00b3 N.")]),

        item("fr-cp-4C-2", "4C", "Electric field",
             "A charge of 2.0 \u00d7 10\u207b\u00b3 C experiences an electric force of 6.0 N. What is the magnitude of the electric field at its location? Give the value with units.",
             ["3.0 \u00d7 10^3 N/C", "3000 N/C", "3.0e3 N/C", "3000 V/m", "3.0 \u00d7 10^3"],
             ["unit: N/C", "tolerance: \u00b11%", "E = F/q"],
             "E = F/q = (6.0 N)/(2.0\u00d710\u207b\u00b3 C) = 3.0\u00d710\u00b3 N/C.",
             "Electric field is force per unit charge; N/C is equivalent to V/m.",
             "easy", "application", cp2e("Ch. 18: Electric Charge and Electric Field"),
             [sub("Write the definition of electric field in terms of force and charge.",
                  ["E = F/q", "E=F/q", "field = force/charge", "E = F / q"],
                  "E = F/q."),
              sub("Compute 6.0 N \u00f7 (2.0\u00d710\u207b\u00b3 C) (give N/C).",
                  ["3000 N/C", "3.0 x 10^3 N/C", "3000"],
                  "= 3.0\u00d710\u00b3 N/C."),
              sub("The unit N/C is equivalent to which other unit of electric field?",
                  ["V/m", "volts per meter", "volt/meter", "V per m"],
                  "N/C = V/m.")]),

        item("fr-cp-4C-3", "4C", "Ohm's law",
             "A 12 V battery drives a current of 3.0 A through a resistor. What is the resistance? Give the value with units.",
             ["4.0 \u03a9", "4 \u03a9", "4.0 ohm", "4 ohms", "4"],
             ["unit: \u03a9", "tolerance: \u00b10.1 \u03a9", "V = I R"],
             "Ohm's law: R = V/I = (12 V)/(3.0 A) = 4.0 \u03a9.",
             "Ohm's law relates voltage, current, and resistance linearly for an ohmic resistor.",
             "easy", "application", cp2e("Ch. 20: Electric Current, Resistance, and Ohm's Law"),
             [sub("State Ohm's law relating V, I, and R.",
                  ["V = I R", "V=IR", "voltage = current x resistance", "V = IR"],
                  "V = I R."),
              sub("Rearrange to solve for resistance R.",
                  ["R = V/I", "R=V/I", "V/I"],
                  "R = V/I."),
              sub("Compute 12 V \u00f7 3.0 A (give \u03a9).",
                  ["4.0 \u03a9", "4 ohm", "4"],
                  "= 4.0 \u03a9.")]),

        item("fr-cp-4C-4", "4C", "Resistors in series",
             "Three resistors of 2.0 \u03a9, 3.0 \u03a9, and 5.0 \u03a9 are connected in series. What is their equivalent resistance? Give the value with units.",
             ["10 \u03a9", "10 ohm", "10 ohms", "10"],
             ["unit: \u03a9", "tolerance: \u00b10.1 \u03a9", "series adds directly"],
             "In series, resistances add: R_eq = 2.0 + 3.0 + 5.0 = 10 \u03a9.",
             "Series resistors share the same current; their voltage drops add, so the resistances add directly.",
             "easy", "application", cp2e("Ch. 21: Circuits and DC Instruments"),
             [sub("How do resistances combine when connected in series?",
                  ["add", "they add", "sum", "add directly"],
                  "Series resistances add: R_eq = R\u2081 + R\u2082 + R\u2083."),
              sub("Compute 2.0 + 3.0 + 5.0 (give \u03a9).",
                  ["10 \u03a9", "10 ohm", "10"],
                  "= 10 \u03a9."),
              sub("Is the current the same through each series resistor? (yes/no)",
                  ["yes", "same", "yes it is"],
                  "Series elements carry identical current.")]),

        item("fr-cp-4C-5", "4C", "Resistors in parallel",
             "Two 4.0 \u03a9 resistors are connected in parallel. What is their equivalent resistance? Give the value with units.",
             ["2.0 \u03a9", "2 \u03a9", "2 ohm", "2 ohms", "2"],
             ["unit: \u03a9", "tolerance: \u00b10.1 \u03a9", "1/Req = 1/R1 + 1/R2"],
             "1/R_eq = 1/4.0 + 1/4.0 = 1/2.0, so R_eq = 2.0 \u03a9.",
             "The parallel equivalent is always smaller than the smallest branch; two equal resistors in parallel give half their value.",
             "medium", "application", cp2e("Ch. 21: Circuits and DC Instruments"),
             [sub("Write the rule for combining two resistors in parallel.",
                  ["1/Req = 1/R1 + 1/R2", "1/R = 1/R1 + 1/R2", "reciprocals add", "1/R_eq=1/R\u2081+1/R\u2082"],
                  "The reciprocals add: 1/R_eq = 1/R\u2081 + 1/R\u2082."),
              sub("For two EQUAL resistors R in parallel, the equivalent is what fraction of R?",
                  ["half", "R/2", "one half", "1/2"],
                  "Two equal resistors in parallel give R/2."),
              sub("Compute the equivalent of two 4.0 \u03a9 resistors in parallel (give \u03a9).",
                  ["2.0 \u03a9", "2 ohm", "2"],
                  "R_eq = 4.0/2 = 2.0 \u03a9.")]),

        item("fr-cp-4C-6", "4C", "Electrical power",
             "A device operates at 120 V and draws 2.0 A. What is its power consumption? Give the value with units.",
             ["240 W", "P = 240 W", "240"],
             ["unit: W", "tolerance: \u00b11 W", "P = I V"],
             "P = I V = (2.0 A)(120 V) = 240 W.",
             "Electrical power equals current times voltage; equivalently P = I\u00b2R = V\u00b2/R.",
             "easy", "application", cp2e("Ch. 20: Electric Current, Resistance, and Ohm's Law"),
             [sub("Write the equation for electrical power in terms of current and voltage.",
                  ["P = I V", "P=IV", "power = current x voltage", "P = IV"],
                  "P = I V."),
              sub("Compute (2.0 A)(120 V) (give W).",
                  ["240 W", "240"],
                  "= 240 W."),
              sub("Give one alternative formula for electrical power using resistance.",
                  ["P = I^2 R", "P = V^2/R", "I^2 R", "V^2/R", "P=I\u00b2R"],
                  "P = I\u00b2R or P = V\u00b2/R (from Ohm's law).")]),

        item("fr-cp-4C-7", "4C", "Capacitance",
             "A 2.0 \u03bcF capacitor is charged to 10 V. How much charge is stored? Give the value with units.",
             ["2.0 \u00d7 10^-5 C", "20 \u03bcC", "20 uC", "2e-5 C", "2.0 \u00d7 10^-5 C"],
             ["unit: C", "tolerance: \u00b15%", "Q = C V"],
             "Q = C V = (2.0\u00d710\u207b\u2076 F)(10 V) = 2.0\u00d710\u207b\u2075 C = 20 \u03bcC.",
             "Capacitance is the charge stored per volt (Q = CV); a farad is one coulomb per volt.",
             "medium", "application", cp2e("Ch. 19: Electric Potential and Electric Field"),
             [sub("Write the relationship between charge, capacitance, and voltage.",
                  ["Q = C V", "Q=CV", "charge = capacitance x voltage", "Q = CV"],
                  "Q = C V."),
              sub("What is 2.0 \u03bcF in farads?",
                  ["2.0 x 10^-6 F", "2e-6 F", "0.000002 F", "2.0 \u00d7 10^-6 F"],
                  "2 \u03bcF = 2\u00d710\u207b\u2076 F."),
              sub("Compute (2.0\u00d710\u207b\u2076)(10) (give C).",
                  ["2.0 x 10^-5 C", "20 \u03bcC", "2e-5 C"],
                  "= 2.0\u00d710\u207b\u2075 C (20 \u03bcC).")]),

        item("fr-cp-4C-8", "4C", "Magnetic force on a moving charge",
             "A charge of 2.0 C moves at 3.0 m/s perpendicular to a 4.0 T magnetic field. What is the magnitude of the magnetic force on it? Give the value with units.",
             ["24 N", "F = 24 N", "24"],
             ["unit: N", "tolerance: \u00b10.5 N", "F = q v B"],
             "For velocity perpendicular to B, F = q v B = (2.0)(3.0)(4.0) = 24 N.",
             "The magnetic force is F = qvB sin\u03b8; it is maximal when v \u22a5 B (sin\u03b8 = 1) and zero when v \u2225 B.",
             "medium", "application", cp2e("Ch. 22: Magnetism"),
             [sub("Write the magnetic-force magnitude for a charge moving perpendicular to B.",
                  ["F = q v B", "F=qvB", "force = qvB", "qvB"],
                  "F = q v B (with v \u22a5 B)."),
              sub("Compute (2.0)(3.0)(4.0) (give N).",
                  ["24 N", "24"],
                  "= 24 N."),
              sub("If the charge moved PARALLEL to B instead, what would the force be?",
                  ["0", "zero", "0 N", "no force"],
                  "F = qvB sin\u03b8 = 0 when v \u2225 B (\u03b8 = 0).")]),

        item("fr-cp-4C-9", "4C", "Galvanic cell potential",
             "For a galvanic cell with a Cu\u00b2\u207a/Cu cathode (E\u00b0 = +0.34 V) and a Zn\u00b2\u207a/Zn anode (E\u00b0 = \u22120.76 V), what is the standard cell potential? Give the value with units.",
             ["+1.10 V", "1.10 V", "1.1 V", "+1.1 V", "1.10"],
             ["unit: V", "tolerance: \u00b10.02 V", "E_cell = E_cathode - E_anode"],
             "E\u00b0_cell = E\u00b0_cathode \u2212 E\u00b0_anode = (+0.34) \u2212 (\u22120.76) = +1.10 V.",
             "A positive E\u00b0_cell means the reaction is spontaneous as written (\u0394G\u00b0 = \u2212nFE\u00b0_cell < 0).",
             "medium", "application", chem2e("Ch. 17: Electrochemistry \u2014 Standard Cell Potentials"),
             [sub("Write the formula for standard cell potential from electrode potentials.",
                  ["E_cell = E_cathode - E_anode", "E\u00b0cell = E\u00b0cathode \u2212 E\u00b0anode", "cathode minus anode", "E=E_cat-E_an"],
                  "E\u00b0_cell = E\u00b0_cathode \u2212 E\u00b0_anode."),
              sub("Substitute (+0.34) \u2212 (\u22120.76).",
                  ["0.34 + 0.76", "+1.10", "1.10", "0.34-(-0.76)"],
                  "Subtracting a negative adds: 0.34 + 0.76 = 1.10 V."),
              sub("Is a cell with E\u00b0_cell = +1.10 V spontaneous? (yes/no)",
                  ["yes", "spontaneous", "yes it is"],
                  "Positive E\u00b0_cell \u2194 negative \u0394G\u00b0 \u2194 spontaneous.")]),

        item("fr-cp-4C-10", "4C", "Electrolysis (Faraday's laws)",
             "How many coulombs of charge are required to deposit 1.0 mol of silver from Ag\u207a (Ag\u207a + e\u207b \u2192 Ag)? Use F = 96,485 C/mol. Give the value with units.",
             ["96485 C", "96500 C", "9.65 \u00d7 10^4 C", "96,485 C", "1 F"],
             ["unit: C", "tolerance: \u00b1500 C", "Q = n F"],
             "Depositing 1 mol Ag needs 1 mol of electrons: Q = nF = (1)(96,485) \u2248 9.65\u00d710\u2074 C.",
             "Faraday's law links moles of electrons to charge; one mole of electrons carries one faraday (96,485 C).",
             "medium", "application", chem2e("Ch. 17: Electrochemistry \u2014 Electrolysis"),
             [sub("How many moles of electrons are needed per mole of Ag\u207a reduced?",
                  ["1", "1 mol", "one"],
                  "Ag\u207a + e\u207b \u2192 Ag uses 1 mol e\u207b per mol Ag."),
              sub("What is the Faraday constant (charge per mole of electrons)?",
                  ["96485 C/mol", "96500 C/mol", "9.65 x 10^4 C/mol", "96485"],
                  "F \u2248 96,485 C/mol."),
              sub("Compute Q = (1 mol)(96,485 C/mol) (give C).",
                  ["96485 C", "96500 C", "9.65 x 10^4 C"],
                  "= 9.65\u00d710\u2074 C.")]),

        item("fr-cp-4C-11", "4C", "Electric potential energy",
             "How much work is required to move a +2.0 C charge through a potential difference of +5.0 V? Give the value with units.",
             ["10 J", "W = 10 J", "10"],
             ["unit: J", "tolerance: \u00b10.5 J", "W = q \u0394V"],
             "W = q\u0394V = (2.0 C)(5.0 V) = 10 J.",
             "The change in electric potential energy equals charge times potential difference (\u0394U = q\u0394V).",
             "easy", "application", cp2e("Ch. 19: Electric Potential and Electric Field"),
             [sub("Write the relationship between work/energy, charge, and potential difference.",
                  ["W = q \u0394V", "W=q\u0394V", "\u0394U = q\u0394V", "energy = charge x voltage"],
                  "W = q\u0394V (= \u0394U)."),
              sub("Compute (2.0 C)(5.0 V) (give J).",
                  ["10 J", "10"],
                  "= 10 J."),
              sub("One volt equals one joule per what unit of charge?",
                  ["coulomb", "C", "per coulomb", "joule per coulomb"],
                  "1 V = 1 J/C.")]),

        item("fr-cp-4C-12", "4C", "Resistivity of a wire",
             "A copper wire has resistivity 1.7 \u00d7 10\u207b\u2078 \u03a9\u00b7m, length 2.0 m, and cross-sectional area 1.0 \u00d7 10\u207b\u2076 m\u00b2. What is its resistance? Give the value with units.",
             ["0.034 \u03a9", "3.4 \u00d7 10^-2 \u03a9", "0.034 ohm", "0.034"],
             ["unit: \u03a9", "tolerance: \u00b15%", "R = \u03c1 L / A"],
             "R = \u03c1L/A = (1.7\u00d710\u207b\u2078)(2.0)/(1.0\u00d710\u207b\u2076) = 3.4\u00d710\u207b\u00b2 \u03a9 = 0.034 \u03a9.",
             "Resistance rises with length and falls with cross-sectional area; resistivity is the material property.",
             "medium", "application", cp2e("Ch. 20: Electric Current, Resistance, and Ohm's Law"),
             [sub("Write the equation for the resistance of a uniform wire.",
                  ["R = \u03c1 L / A", "R = rho L / A", "R=\u03c1L/A", "\u03c1L/A"],
                  "R = \u03c1L/A."),
              sub("Compute (1.7\u00d710\u207b\u2078)(2.0)/(1.0\u00d710\u207b\u2076) (give \u03a9).",
                  ["0.034 \u03a9", "3.4 x 10^-2 \u03a9", "0.034"],
                  "= 3.4\u00d710\u207b\u00b2 \u03a9."),
              sub("Doubling the wire's cross-sectional area would do what to its resistance?",
                  ["halve", "halves", "cut in half", "halve it"],
                  "R \u221d 1/A, so doubling A halves R.")]),
    ]


# ===========================================================================
#  4D -- How light and sound interact with matter
# ===========================================================================

def _cat_4D() -> list:
    return [
        item("fr-cp-4D-1", "4D", "Wave speed, frequency, wavelength",
             "A sound wave has a frequency of 500 Hz and a wavelength of 0.68 m. What is its speed? Give the value with units.",
             ["340 m/s", "v = 340 m/s", "340"],
             ["unit: m/s", "tolerance: \u00b12 m/s", "v = f \u03bb"],
             "v = f\u03bb = (500 Hz)(0.68 m) = 340 m/s.",
             "The wave equation v = f\u03bb ties speed, frequency, and wavelength; 340 m/s is roughly the speed of sound in air.",
             "easy", "application", cp2e("Ch. 16: Oscillatory Motion and Waves"),
             [sub("Write the wave equation relating speed, frequency, and wavelength.",
                  ["v = f \u03bb", "v=f\u03bb", "speed = frequency x wavelength", "v = f\u00b7\u03bb"],
                  "v = f\u03bb."),
              sub("Compute (500 Hz)(0.68 m) (give m/s).",
                  ["340 m/s", "340"],
                  "= 340 m/s."),
              sub("If frequency doubles at constant wave speed, what happens to wavelength?",
                  ["halves", "halved", "cut in half", "decreases by half"],
                  "v is fixed, so \u03bb = v/f halves when f doubles.")]),

        item("fr-cp-4D-2", "4D", "Sound intensity and decibels",
             "A sound has intensity 1.0 \u00d7 10\u207b\u2076 W/m\u00b2. Using I\u2080 = 1.0 \u00d7 10\u207b\u00b9\u00b2 W/m\u00b2, what is its sound intensity level? Give the value in decibels.",
             ["60 dB", "\u03b2 = 60 dB", "60"],
             ["unit: dB", "tolerance: \u00b11 dB", "\u03b2 = 10 log(I/I0)"],
             "\u03b2 = 10 log(I/I\u2080) = 10 log(10\u207b\u2076/10\u207b\u00b9\u00b2) = 10 log(10\u2076) = 10(6) = 60 dB.",
             "The decibel scale is logarithmic: each factor-of-10 increase in intensity adds 10 dB.",
             "medium", "application", cp2e("Ch. 17: Physics of Hearing"),
             [sub("Write the formula for sound intensity level in decibels.",
                  ["\u03b2 = 10 log(I/I0)", "10 log(I/I0)", "\u03b2=10log(I/I\u2080)", "beta = 10 log(I/I0)"],
                  "\u03b2 = 10 log\u2081\u2080(I/I\u2080)."),
              sub("Compute the ratio I/I\u2080 = 10\u207b\u2076 / 10\u207b\u00b9\u00b2.",
                  ["10^6", "1000000", "1e6", "10\u2076"],
                  "10\u207b\u2076/10\u207b\u00b9\u00b2 = 10\u2076."),
              sub("Evaluate 10 log(10\u2076) (give dB).",
                  ["60 dB", "60"],
                  "log(10\u2076) = 6, so \u03b2 = 60 dB.")]),

        item("fr-cp-4D-3", "4D", "Doppler effect",
             "A sound source moves toward a stationary observer. Is the frequency the observer hears higher or lower than the emitted frequency? Answer in one word.",
             ["higher", "increases", "greater", "raised"],
             ["higher", "increases", "shorter wavelength"],
             "Higher. Motion toward the observer compresses the wavefronts, shortening the wavelength and raising the observed frequency.",
             "The Doppler effect shifts perceived frequency up for approach and down for recession; it underlies the changing pitch of a passing siren.",
             "medium", "recall", cp2e("Ch. 17: Physics of Hearing \u2014 Doppler Effect"),
             [sub("When the source approaches, what happens to the spacing (wavelength) of the wavefronts ahead of it?",
                  ["compressed", "shorter", "decreases", "bunched up"],
                  "The wavefronts pile up, shortening the wavelength."),
              sub("At fixed wave speed, a shorter wavelength corresponds to a higher or lower frequency?",
                  ["higher", "higher frequency", "greater"],
                  "f = v/\u03bb, so shorter \u03bb means higher f."),
              sub("Therefore the observed pitch is ____ than emitted. (one word)",
                  ["higher", "greater", "raised"],
                  "Approach \u2192 higher pitch.")]),

        item("fr-cp-4D-4", "4D", "Standing waves and harmonics",
             "A string fixed at both ends is 1.0 m long, and waves travel on it at 200 m/s. What is the fundamental frequency? Give the value with units.",
             ["100 Hz", "f_1 = 100 Hz", "100"],
             ["unit: Hz", "tolerance: \u00b11 Hz", "f1 = v/(2L)"],
             "For a string fixed at both ends the fundamental wavelength is \u03bb\u2081 = 2L = 2.0 m, so f\u2081 = v/\u03bb\u2081 = 200/2.0 = 100 Hz.",
             "The fundamental fits half a wavelength between the fixed ends; higher harmonics are integer multiples of f\u2081.",
             "medium", "application", cp2e("Ch. 16: Oscillatory Motion and Waves \u2014 Standing Waves"),
             [sub("For a string fixed at both ends, the fundamental wavelength equals how many times the length L?",
                  ["2L", "twice", "2 L", "two times L"],
                  "\u03bb\u2081 = 2L (half a wavelength spans the string)."),
              sub("Compute \u03bb\u2081 = 2L for L = 1.0 m (give m).",
                  ["2.0 m", "2 m", "2.0"],
                  "\u03bb\u2081 = 2(1.0) = 2.0 m."),
              sub("Compute f\u2081 = v/\u03bb\u2081 = 200/2.0 (give Hz).",
                  ["100 Hz", "100"],
                  "= 100 Hz.")]),

        item("fr-cp-4D-5", "4D", "Electromagnetic spectrum",
             "Which has more energy per photon: an X-ray or a radio wave? Answer with the type of radiation.",
             ["X-ray", "X-rays", "x-ray", "xray", "xrays"],
             ["X-ray", "higher frequency", "E = h f"],
             "X-ray. Photon energy E = hf increases with frequency, and X-rays have a far higher frequency than radio waves.",
             "Across the EM spectrum, higher frequency (shorter wavelength) means higher photon energy: radio < IR < visible < UV < X-ray < gamma.",
             "easy", "recall", cp2e("Ch. 24: Electromagnetic Waves"),
             [sub("Write the equation for the energy of a single photon.",
                  ["E = h f", "E=hf", "energy = h times frequency", "E = hf"],
                  "E = hf, where h is Planck's constant."),
              sub("Which has the higher frequency, X-rays or radio waves?",
                  ["X-rays", "x-ray", "xrays"],
                  "X-rays have a much higher frequency than radio waves."),
              sub("Higher frequency therefore means higher or lower photon energy?",
                  ["higher", "higher energy", "greater"],
                  "E \u221d f, so higher frequency \u2192 higher energy \u2192 X-rays win.")]),

        item("fr-cp-4D-6", "4D", "Refraction (Snell's law)",
             "Light passes from air (n = 1.0) into glass (n = 1.5) with an angle of incidence of 30\u00b0. What is the angle of refraction? Give the value in degrees.",
             ["19.5\u00b0", "19.5 degrees", "19.5", "20\u00b0", "19\u00b0"],
             ["unit: \u00b0", "tolerance: \u00b11\u00b0", "n1 sin\u03b81 = n2 sin\u03b82"],
             "Snell's law: n\u2081 sin\u03b8\u2081 = n\u2082 sin\u03b8\u2082 \u2192 sin\u03b8\u2082 = (1.0)(sin 30\u00b0)/1.5 = 0.5/1.5 = 0.333, so \u03b8\u2082 = arcsin(0.333) \u2248 19.5\u00b0.",
             "Light bends toward the normal when entering a denser (higher-n) medium, so the refracted angle is smaller than the incident angle.",
             "medium", "application", cp2e("Ch. 25: Geometric Optics \u2014 The Law of Refraction"),
             [sub("State Snell's law of refraction.",
                  ["n1 sin\u03b81 = n2 sin\u03b82", "n\u2081sin\u03b8\u2081=n\u2082sin\u03b8\u2082", "n1 sin(theta1) = n2 sin(theta2)"],
                  "n\u2081 sin\u03b8\u2081 = n\u2082 sin\u03b8\u2082."),
              sub("Solve for sin\u03b8\u2082 with n\u2081 = 1.0, \u03b8\u2081 = 30\u00b0, n\u2082 = 1.5.",
                  ["0.333", "0.33", "1/3", "0.5/1.5"],
                  "sin\u03b8\u2082 = (1.0)(0.5)/1.5 = 0.333."),
              sub("Take arcsin(0.333) (give degrees).",
                  ["19.5\u00b0", "19.5 degrees", "19.5", "20\u00b0"],
                  "\u03b8\u2082 \u2248 19.5\u00b0.")]),

        item("fr-cp-4D-7", "4D", "Total internal reflection",
             "For light traveling from glass (n = 1.5) toward air (n = 1.0), what is the critical angle for total internal reflection? Give the value in degrees.",
             ["41.8\u00b0", "42\u00b0", "41.8 degrees", "41.8", "42 degrees"],
             ["unit: \u00b0", "tolerance: \u00b11\u00b0", "sin\u03b8c = n2/n1"],
             "At the critical angle the refracted ray grazes at 90\u00b0: sin\u03b8_c = n\u2082/n\u2081 = 1.0/1.5 = 0.667, so \u03b8_c = arcsin(0.667) \u2248 41.8\u00b0.",
             "Total internal reflection occurs only going from a denser to a less dense medium, above the critical angle \u2014 the basis of fiber optics.",
             "hard", "application", cp2e("Ch. 25: Geometric Optics \u2014 Total Internal Reflection"),
             [sub("At the critical angle, what is the angle of refraction?",
                  ["90\u00b0", "90 degrees", "90"],
                  "The refracted ray travels along the surface at 90\u00b0."),
              sub("Write the equation for the critical angle (from medium 1 to medium 2).",
                  ["sin\u03b8c = n2/n1", "sin(theta_c) = n2/n1", "\u03b8c = arcsin(n2/n1)", "sin\u03b8c=n\u2082/n\u2081"],
                  "sin\u03b8_c = n\u2082/n\u2081."),
              sub("Compute arcsin(1.0/1.5) (give degrees).",
                  ["41.8\u00b0", "42\u00b0", "41.8"],
                  "arcsin(0.667) \u2248 41.8\u00b0.")]),

        item("fr-cp-4D-8", "4D", "Thin lens equation",
             "An object is placed 15 cm from a converging lens of focal length 10 cm. Where is the image formed? Give the image distance with units.",
             ["30 cm", "d_i = 30 cm", "0.30 m", "30"],
             ["unit: cm", "tolerance: \u00b10.5 cm", "1/f = 1/do + 1/di"],
             "1/f = 1/d\u2092 + 1/d\u1d62 \u2192 1/d\u1d62 = 1/10 \u2212 1/15 = 3/30 \u2212 2/30 = 1/30, so d\u1d62 = 30 cm (real image).",
             "A positive image distance means a real image forms on the opposite side of the lens.",
             "medium", "application", cp2e("Ch. 25: Geometric Optics \u2014 Thin Lenses"),
             [sub("Write the thin lens equation.",
                  ["1/f = 1/do + 1/di", "1/f = 1/d_o + 1/d_i", "1/f=1/do+1/di"],
                  "1/f = 1/d\u2092 + 1/d\u1d62."),
              sub("Solve for 1/d\u1d62 with f = 10 cm and d\u2092 = 15 cm.",
                  ["1/30", "1/10 - 1/15", "0.0333", "1/30 cm^-1"],
                  "1/d\u1d62 = 1/10 \u2212 1/15 = 1/30."),
              sub("Invert 1/d\u1d62 = 1/30 to find d\u1d62 (give cm).",
                  ["30 cm", "30"],
                  "d\u1d62 = 30 cm.")]),

        item("fr-cp-4D-9", "4D", "Magnification",
             "For the lens above (image distance 30 cm, object distance 15 cm), what is the magnification (include sign)? Give the numeric value.",
             ["-2", "-2.0", "\u22122", "\u22122.0", "-2x"],
             ["dimensionless", "exact", "m = -di/do"],
             "m = \u2212d\u1d62/d\u2092 = \u221230/15 = \u22122. The negative sign indicates an inverted image, twice the object's size.",
             "Magnification magnitude is the size ratio; a negative sign denotes an inverted (real) image.",
             "medium", "application", cp2e("Ch. 25: Geometric Optics \u2014 Image Formation"),
             [sub("Write the magnification formula in terms of image and object distances.",
                  ["m = -di/do", "m = -d_i/d_o", "m=-di/do", "-di/do"],
                  "m = \u2212d\u1d62/d\u2092."),
              sub("Compute \u221230/15.",
                  ["-2", "-2.0", "\u22122"],
                  "= \u22122."),
              sub("What does the negative sign tell you about the image orientation?",
                  ["inverted", "upside down", "it is inverted", "flipped"],
                  "A negative magnification means the image is inverted.")]),

        item("fr-cp-4D-10", "4D", "Infrared spectroscopy",
             "In an IR spectrum, a strong absorption near 1700 cm\u207b\u00b9 is the signature of which bond? Give the bond.",
             ["C=O", "carbonyl", "carbonyl (C=O)", "C=O (carbonyl)", "c=o"],
             ["C=O", "carbonyl", "~1700 cm^-1"],
             "C=O (the carbonyl group). The strong stretch near 1700 cm\u207b\u00b9 identifies aldehydes, ketones, carboxylic acids, esters, and amides.",
             "IR absorptions arise from bond-stretching vibrations; the carbonyl gives one of the strongest, most diagnostic IR peaks.",
             "medium", "recall", ochem("Ch. 12: Structure Determination \u2014 Infrared Spectroscopy"),
             [sub("IR absorptions are caused by what kind of molecular motion?",
                  ["bond vibrations", "vibrations", "stretching", "bond stretching/bending"],
                  "IR light excites bond vibrations (stretching and bending)."),
              sub("A strong, sharp peak near 1700 cm\u207b\u00b9 is characteristic of which functional feature?",
                  ["carbonyl", "C=O", "carbonyl group"],
                  "The ~1700 cm\u207b\u00b9 band is the carbonyl (C=O) stretch."),
              sub("Name one functional group that contains a C=O and shows this peak.",
                  ["ketone", "aldehyde", "carboxylic acid", "ester", "amide"],
                  "Any carbonyl compound (ketone, aldehyde, carboxylic acid, ester, amide).")]),

        item("fr-cp-4D-11", "4D", "UV-Vis absorption and conjugation",
             "As the extent of conjugation in a molecule increases, does its wavelength of maximum UV-Vis absorption shift to longer or shorter wavelengths? Answer in one word.",
             ["longer", "increases", "red", "red-shift", "redshift"],
             ["longer", "red shift", "smaller HOMO-LUMO gap"],
             "Longer. More conjugation lowers the HOMO\u2013LUMO energy gap, so a lower-energy (longer-wavelength) photon is absorbed \u2014 a red shift.",
             "Extended conjugation delocalizes \u03c0 electrons and narrows the electronic gap, which is why highly conjugated molecules (e.g., \u03b2-carotene) are colored.",
             "medium", "application", ochem("Ch. 14: Conjugated Compounds \u2014 UV Spectroscopy"),
             [sub("Absorbing a UV-Vis photon promotes an electron across which energy gap?",
                  ["HOMO-LUMO", "HOMO to LUMO", "HOMO\u2013LUMO gap", "the pi to pi* gap"],
                  "The electron jumps from the HOMO to the LUMO."),
              sub("More conjugation makes the HOMO\u2013LUMO gap larger or smaller?",
                  ["smaller", "decreases", "narrower"],
                  "Extended conjugation lowers (narrows) the gap."),
              sub("A smaller energy gap means absorption at longer or shorter wavelength?",
                  ["longer", "longer wavelength", "increases"],
                  "Lower energy \u2192 longer wavelength (E = hc/\u03bb).")]),
    ]


def build_items() -> list:
    items: list = []
    items += _cat_4A()
    items += _cat_4B()
    items += _cat_4C()
    items += _cat_4D()
    return items


def main() -> int:
    items = build_items()
    with open(OUT, "w", encoding="utf-8") as fh:
        json.dump(items, fh, ensure_ascii=False, indent=2)
        fh.write("\n")
    with open(OUT, "r", encoding="utf-8") as fh:
        reloaded = json.load(fh)
    print(f"Wrote {OUT} ({len(reloaded)} items).\n")

    sys.path.insert(0, HERE)
    import validate_free_response_chem_phys as V
    return V.main(["validate", OUT])


if __name__ == "__main__":
    raise SystemExit(main())
